### ISSUE TITLE
missing index.d.ts

### ISSUE THREAD

**Issue by jdanyow** [eustatos/pure-md5#7]
package.json identifies the location of the TypeScript definitions:

https://github.com/eustatos/pure-md5/blob/c79b77773f335a94efc7605edf75755eb7ff0bea/package.json#L6

But `lib/index.d.ts` doesn't seem to have been published. I verified locally, but you can also [confirm on jsdelivr](https://www.jsdelivr.com/package/npm/pure-md5?path=lib) for convenience.

**Comment by eustatos** [comment]
@idanyow, thank you for your comment. Fixed.
In jsdelivr you can not see definitions files. Please check in `node_modules` after installation.
